name: check
on: push
jobs:
    compile:
        name: compile
        runs-on: ubuntu-18.04
        steps:
          - uses: actions/checkout@v1.0.0
          - run: g++ --version
          - run: cd ICPC
          - run: ls -la
          - run: cd script
          - run: ls -la
          - run: ./compile.sh