name: check
on: push
jobs:
  compile:
    name: compile
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1.0.0
      - run: g++ --version
      - run: cd ICPC/ && bash script/gen.sh
      - run: pwd
      - run: cd ICPC/
      - run: pwd
      - run: cd ICPC/ && ls -la
      - run: ls -la
      - run: bash script/compile.sh
